version: '3'
services:
  zookeeper:
    image: mocchi/fedora-kafka:latest
    command: '/root/kafka_2.12-1.1.1/bin/zookeeper-server-start.sh /root/kafka_2.12-1.1.1/config/zookeeper.properties'
  kafka1:
    image: mocchi/fedora-kafka:latest
    depends_on:
      - 'zookeeper'
    environment:
      BROKER_ID: 1
      KAFKA_HOST: kafka1
    volumes:
      - './bin:/root/bin'
    command: 'sh /root/bin/run_kafka.sh'
  kafka2:
    image: mocchi/fedora-kafka:latest
    depends_on:
      - 'zookeeper'
    environment:
      BROKER_ID: 2
      KAFKA_HOST: kafka2
    volumes:
      - './bin:/root/bin'
    command: 'sh /root/bin/run_kafka.sh'
  kafka-chat-cache:
    image: redis:4
  gyazo-server:
    build:
      context: ./
      dockerfile: ./extra/container/gyazo.Dockerfile
    image: mocchi/gyazo
    environment:
      KAFKA_HOST: 'kafka1:9092'
      OREOREGYAZO_DEBUG: 'false'
      OREOREGYAZO_ALLOW_CORS_HOST: 'localhost:8080'
      WAIT_HOST: 'kafka1'
      WAIT_PORT: 9092
    ports:
      - '3000:3000'
    depends_on:
      - 'kafka1'
  kafka-chat:
    build:
      context: ./
      dockerfile: ./extra/container/kafka_chat.Dockerfile 
    image: mocchi/kafka_chat
    ports:
      - '8080:8080'
    depends_on:
      - 'kafka1'
      - 'kafka2'
      - 'kafka-chat-cache'
    volumes:
      - './:/root/chat'
    command: sh /root/chat/bin/dev.sh