version: '3'
services:
  zookeeper:
    image: mocchi/fedora-kafka:latest
    command: '/root/kafka_2.12-1.1.1/bin/zookeeper-server-start.sh /root/kafka_2.12-1.1.1/config/zookeeper.properties'
  kafka1:
    image: mocchi/fedora-kafka:latest
    depends_on:
      - 'zookeeper'
    environment:
      BROKER_ID: 1
      KAFKA_HOST: kafka1
    volumes:
      - './bin:/root/bin'
    command: 'sh /root/bin/run_kafka.sh'
  kafka2:
    image: mocchi/fedora-kafka:latest
    depends_on:
      - 'zookeeper'
    environment:
      BROKER_ID: 2
      KAFKA_HOST: kafka2
    volumes:
      - './bin:/root/bin'
    command: 'sh /root/bin/run_kafka.sh'
  kafka-chat:
    image: fedora:28
    ports:
      - '8080:8080'
    depends_on:
      - 'kafka1'
      - 'kafka2'
    volumes:
      - './:/root/chat'
    command: sh /root/chat/bin/dev.sh